
server:
  port: 10001
  servlet:
    context-path: /example

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mymxdxy!@#
    url: jdbc:mysql://101.200.132.222:3306?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration.map-underscore-to-camel-case: true